dependencies:
  cached_network_image: ^3.3.1 
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.3
  sqflite: ^2.3.2
  webview_flutter: ^4.10.0

description: Podistica Arona app.

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  assets:
    - data_repo/img/ic_launcher.png
    - data_repo/img/social/facebook.png
    - data_repo/img/social/instagram.png
    - data_repo/img/social/google_plus.png
    - data_repo/img/social/linkedin.png
    - data_repo/img/social/twitter.png
    - data_repo/img/logo_top.png
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: data_repo/img/logo_top.png
  ios: true

name: runpa
publish_to: none
version: 1.0.3
